name: Pull request workflow

on:
  pull_request:

jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-20.04
    env:
      GRADLE_OPTS: -Dorg.gradle.workers.max=2 -Dorg.gradle.parallel=true -Dkotlin.compiler.execution.strategy=in-process -Dorg.gradle.jvmargs="-Xmx5120m -XX:+UseParallelGC -XX:MaxMetaspaceSize=2536m -XX:+HeapDumpOnOutOfMemoryError"

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Check out code
        uses: actions/checkout@v4
        with:
          fetch-depth: '0'

      - name: Release tag
        run: |
          git describe --tags --always --first-parent
          git tag

      - name: Setup java
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: 11

      - name: Run Android checks
        run: ./gradlew check

      - name: Upload reports
        uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: Reports
          path: '**/build/reports/*'
          retention-days: 2
